[platformio]
default_envs = usb

[env]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
board_build.filesystem = littlefs
board_build.partitions = partitions.csv
monitor_speed = 115200

; --- Board Specific Configuration for ESP32-S3-N16R8 ---
; Enable 16MB Flash and 8MB Octal PSRAM
board_build.flash_size = 16MB
board_build.arduino.memory_type = qio_opi

; USB Serial Output Fix for ESP32-S3
build_flags = 
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D BOARD_HAS_PSRAM
    -D CONFIG_ESP_CONSOLE_SECONDARY_USB_SERIAL_GPIO=48
    -D CONFIG_ASYNC_TCP_RUNNING_CORE=0
    -D CONFIG_ASYNC_TCP_STACK_SIZE=8192

lib_deps =
    mathieucarbou/ESPAsyncWebServer
    mathieucarbou/AsyncTCP
    https://github.com/xreef/PCF8575_library.git
    adafruit/Adafruit NeoPixel
    bblanchon/ArduinoJson @ ^7.0.4
    h2zero/NimBLE-Arduino
lib_ignore = WebServer

[env:usb]
upload_protocol = esptool

[env:ota]
upload_protocol = espota
upload_port = 192.168.1.153 ; <-- Update this to your current IP address from the Serial Monitor
upload_flags = 
    --port=3232
    --auth=Mitchell2019!